#!/bin/bash
if ! readlink $BASH_SOURCE >/dev/null
then
    echo please use this from symlink
    echo available commands are below
    echo
    cd $(cd $(dirname "${BASH_SOURCE:-$0}"); pwd)
    ls -d */|tr -d /|awk '{print "- " $1}'
    exit 1
fi

SCRIPT_DIR=$(dirname $(readlink $BASH_SOURCE))
TOOL_NAME=$(basename $BASH_SOURCE)
YML=$SCRIPT_DIR/$TOOL_NAME/docker-compose.yml
docker-compose -f $YML run --service-ports --rm --name $TOOL_NAME -u $UID -e "COLUMNS=$(tput cols)" -e "LINES=$(tput lines)" tool "$@" || \
docker-compose -f $YML run --rm --name $TOOL_NAME -u $UID -e "COLUMNS=$(tput cols)" -e "LINES=$(tput lines)" tool "$@"
