version: '3.7'
services:
  tool:
    build: .
    tty: true
    network_mode: "host"
    # ports:
    #   - "3000:3000"
    # env_file:
    #  - .env
    environment:
      - HOME=/home/$USER
    volumes:
      - $PWD:/work
      - $HOME:/home/$USER
    working_dir: /work
    entrypoint:
      - bash
    # command: --help
    # command: tail -f /dev/null
    stop_signal: SIGKILL

